### ISSUE TITLE
Implicit Wait for API request.

### ISSUE THREAD

**Issue by bc-nikhil** [authorjapps/zerocode-hello-world#22]
Hi Team,

I need to test a few API's which may take time for response, So there is no specific response time for those API can we add some implicit wait time in our Zerocode where we will define some max response time for API's and whenever we will get a response we will move to the next step.

**Comment by authorjapps** [comment]
Please refer the Wiki for usage-
https://github.com/authorjapps/zerocode/wiki/HTTP-max-implicit-wait-and-connection-timeout

**Comment by authorjapps** [comment]
Available in `1.3.13` and higher.
https://github.com/authorjapps/zerocode/releases/tag/zerocode-tdd-parent-1.3.13
