### ISSUE TITLE
SSlContextBuilder has been deprecated

### ISSUE THREAD

**Issue by aghorpade** [authorjapps/zerocode-hello-world#23]
I am getting a warning that Apache conn SSL ContextBUilder has been deprecated. 

Can we update code to remove deprecated dependancy and use latest code from apache.

![image](https://user-images.githubusercontent.com/5318345/65419116-e3cb7a80-ddf5-11e9-849d-feed600d34fc.png)

**Comment by Shilpa-Perera** [comment]
I have been looking at this issue and it appears that the HttpCLient SSLContexts class being moved from ```org.apache.http.conn.ssl.SSLContexts``` to ```org.apache.http.ssl.SSLContexts```. I think we should change the import in CustomHttpClient.java class
