### ISSUE TITLE
Set up CI build with Maven and Gradle

### ISSUE THREAD

**Issue by prayascoriolis** [authorjapps/zerocode-hello-world#39]
Set up Continuous Integration (CI) for the zerocode-hello-world repository with two separate workflows: one for Maven builds and another for Gradle builds. This includes creating and configuring the necessary yml files in GitHub Actions workflows.

**Comment by authorjapps** [comment]
https://github.com/authorjapps/zerocode-hello-world/actions/workflows/gradle-build.yml
- Gradle build has failed due to some config issue I guess. Have a look at the above link @prayascoriolis .

**Comment by prayascoriolis** [comment]
I found the build failure was due to an incorrect Zerocode dependency version in build.gradle. Updated from 1.3.6 to 1.3.43, which should resolve the issue. I've made a new pr for this change: #41

**Comment by authorjapps** [comment]
Done.
Both maven and Gradle set up done.
Thank you for this.

This ticket can be closed now.
